markdown: rdiscount
permalink: /:title/
url: http://bestapp8.com
name: BestApp8.com
author: BB
qq: 171625386
email: x.fantasy@gmail.com
duoshuo: bestapp8
github: xfantasy
pygments: true
safe: true
paginate: 10
about: "各种软件使用技巧、开源框架使用、系统操作方法"
